import React from 'react';
import type { Metadata } from "next";
import "./globals.css";
import Header from './header';
import Footer from './footer';
import Introduction from './components/Introduction';
import Video from './components/Video';
import Project from './components/Project';

export const metadata: Metadata = {
  title: "Loïc Butor",
  description: "Generated by create next app",
};

const projects = [
  {
    href: "https://github.com/bulofed/Astra",
    imgSrc: "/astra.png",
    description: "Astra is an isometrical RPG game where the goal is to beat every level and get to the end of the game. You beat the levels by killing every enemies in the level. The game is made in Python, using the PyGame FOSS library and is a school project."
  },
  {
    href: "https://github.com/bulofed/Cryptr",
    imgSrc: "/cryptr.png",
    description: "Cryptr is a web escape game with multiple levels. The goal is to escape the room by solving puzzles. The game is made with Nuxt and MongoDB."
  }
  // Add more projects as needed
];

const Page = () => {
  return (
    <html>
      <body>
        <div className="flex flex-col min-h-screen bg-zinc-900 text-zinc-50 px-8">
          <Header />
          <main className="flex-grow max-w-5xl mx-auto w-full flex flex-col gap-12 py-12">
            <Introduction />
            <Video />
            {projects.map((project, index) => (
              <Project 
                key={index}
                href={project.href}
                imgSrc={project.imgSrc}
                description={project.description}
              />
            ))}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
};

export default Page;
